### ISSUE TITLE
Installation guide missing some command.

### ISSUE THREAD

**Issue by opxz7148** [Ichi1234/ku-polls#56]
In installation guide. The command that activate virtual environment is missing.

**Comment by Ichi1234** [comment]
Thank I fix it in [I forget how to activate venv in README.md
](https://github.com/Ichi1234/ku-polls/commit/6c4749c88fbf5aa838168a5161ae3615df2fec50)

**Comment by Ichi1234** [comment]
Oh wait I misunderstood!! I think you mean in README.md
