### ISSUE TITLE
Login - Logout button UI need some improvement

### ISSUE THREAD

**Issue by opxz7148** [Ichi1234/ku-polls#57]
Login look better as a button then a hyperlink. Also Login a Logout button layout is a bit weird. It's should align with polls list or maybe move it to corner of the page. 
Optional: Make login/logout button bigger.

**Comment by Ichi1234** [comment]
In my opinion, the current user interface (UI) is already good. Therefore, I think I'm not going to change it. I tried to change it before but I disliked it.

**Comment by Ichi1234** [comment]
Did you have a poor user experience because of the login button? If it's not about the style but bad UX design, I'm going to change it.

**Comment by opxz7148** [comment]
Login/Logout layout doesn't effect much but login hyperlink and small logout button cause a bad user experience. I suggest you should change it to button same size as view button.

**Comment by Ichi1234** [comment]
I will increase the button size. However, I will not change the login hyperlink to something else. I think the Hyperlink doesn't cause a bad user experience. (See the document [here](https://usabilitygeek.com/hyperlink-usability-guidelines-usable-links/))

**Comment by Ichi1234** [comment]
Should I change the color to make it look like the "View" button?

Before:
![image](https://github.com/user-attachments/assets/a4b43ca7-a378-4e5d-8ae8-d9a750a7427d)

After:
![image](https://github.com/user-attachments/assets/556a8a52-8ce8-49d7-909b-386893c28212)

My dog:
![snow_look](https://github.com/user-attachments/assets/88e990c4-86a8-4775-af52-5d0468d860ca)

**Comment by opxz7148** [comment]
Imo first one look better. Run said "Last one look delicious"

**Comment by Ichi1234** [comment]
I am going to Run's house to eat her cat. Please, do not lock the door.

**Comment by Ichi1234** [comment]
On the way~~~
